require 'app/geometry/point_set.rb'
require 'app/rendering/point_renderer.rb'
require 'app/rendering/polygon_renderer.rb'
require 'app/geometry/transforms.rb'
require 'app/geometry/cube.rb'
require 'app/bootstrap/app.rb'