require 'lib/minitest.rb'
require 'lib/vector_helpers.rb'
require 'spec/vector_spec.rb'
require 'app/geometry/point_set.rb'
require 'app/rendering/point_renderer.rb'
require 'spec/geometry/point_set_spec.rb'
require 'app/bootstrap/app_test.rb'
